name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Bawo ni
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: We're working to resolve your issue! 
       
